import {MigrationInterface, QueryRunner} from "typeorm";

export class IvfMigration1660082598906 implements MigrationInterface {
    name = 'IvfMigration1660082598906'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP CONSTRAINT "FK_00404eb1e33a903eecaa92652f8"`);
        await queryRunner.query(`CREATE TABLE "biopsy" ("id" SERIAL NOT NULL, "old_id" character varying, "createdBy" character varying(300) NOT NULL DEFAULT 'admin', "lastChangedBy" character varying(300), "deleted_at" TIMESTAMP, "deletedBy" character varying(300), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying, "one" character varying, "two" character varying, "three" character varying, "four" character varying, "five" character varying, "six" character varying, "seven" character varying, "eight" character varying, "nine" character varying, "ten" character varying, "eleven" character varying, "twelve" character varying, "assessment_id" integer, CONSTRAINT "PK_7404f0555c615ee4c74a21f4d74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "icsi_day_record" ("id" SERIAL NOT NULL, "old_id" character varying, "createdBy" character varying(300) NOT NULL DEFAULT 'admin', "lastChangedBy" character varying(300), "deleted_at" TIMESTAMP, "deletedBy" character varying(300), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying, "one_pn" character varying, "two_pn" character varying, "three_pn" character varying, "mil" character varying, "ml" character varying, "gv" character varying, "others" character varying, "comment" character varying, "witness" character varying, "embryologist" character varying, "icsi_id" integer, CONSTRAINT "PK_c46aa8d81ada55ee961078b1d49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cell_info" ("id" SERIAL NOT NULL, "old_id" character varying, "createdBy" character varying(300) NOT NULL DEFAULT 'admin', "lastChangedBy" character varying(300), "deleted_at" TIMESTAMP, "deletedBy" character varying(300), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "volume" real, "cells" character varying, "density" character varying, "motility" character varying, "prog" character varying, "abnor" real, "agglutination" real, "sperm_prep_id" integer, CONSTRAINT "PK_a7cce74678521f55e96e7622dd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "embryologist"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "ivf_embryo_trans_record_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "withdrawalMethod"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "createdBy" character varying(300) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "lastChangedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "deletedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "createdBy" character varying(300) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "lastChangedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "deletedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD "ivf_transfer_id" integer`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "createdBy" character varying(300) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "lastChangedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "deletedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "staff_id" integer`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "createdBy" character varying(300) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "lastChangedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "deletedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" ADD "oocyteComment" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "createdBy" character varying(300) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "lastChangedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "deletedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "createdBy" character varying(300) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "lastChangedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "deletedBy" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "instructionsForLab"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "instructionsForLab" character varying`);
        await queryRunner.query(`ALTER TABLE "biopsy" ADD CONSTRAINT "FK_e578cd7f6f69c5c245c8a4dcdf6" FOREIGN KEY ("assessment_id") REFERENCES "embryo_assessment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" ADD CONSTRAINT "FK_9b870f9b022a80d96de3bca3358" FOREIGN KEY ("ivf_transfer_id") REFERENCES "ivf_embryo_transfer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD CONSTRAINT "FK_9bcb4fb56533d4f00e702171d55" FOREIGN KEY ("staff_id") REFERENCES "staff_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "icsi_day_record" ADD CONSTRAINT "FK_c017044ba730946a52e16658928" FOREIGN KEY ("icsi_id") REFERENCES "ivf_icsi"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cell_info" ADD CONSTRAINT "FK_a48573b8204895595624e4ae55c" FOREIGN KEY ("sperm_prep_id") REFERENCES "ivf_sperm_preparation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cell_info" DROP CONSTRAINT "FK_a48573b8204895595624e4ae55c"`);
        await queryRunner.query(`ALTER TABLE "icsi_day_record" DROP CONSTRAINT "FK_c017044ba730946a52e16658928"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP CONSTRAINT "FK_9bcb4fb56533d4f00e702171d55"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP CONSTRAINT "FK_9b870f9b022a80d96de3bca3358"`);
        await queryRunner.query(`ALTER TABLE "biopsy" DROP CONSTRAINT "FK_e578cd7f6f69c5c245c8a4dcdf6"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "instructionsForLab"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" ADD "instructionsForLab" integer`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "lastChangedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_treatment" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "lastChangedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "oocyteComment"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "lastChangedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_icsi" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "staff_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "lastChangedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "ivf_transfer_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "lastChangedBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer_record" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "lastChangedBy"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "embryo_assessment" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_sperm_preparation" ADD "withdrawalMethod" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "ivf_embryo_trans_record_id" integer`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD "embryologist" character varying`);
        await queryRunner.query(`DROP TABLE "cell_info"`);
        await queryRunner.query(`DROP TABLE "icsi_day_record"`);
        await queryRunner.query(`DROP TABLE "biopsy"`);
        await queryRunner.query(`ALTER TABLE "ivf_embryo_transfer" ADD CONSTRAINT "FK_00404eb1e33a903eecaa92652f8" FOREIGN KEY ("ivf_embryo_trans_record_id") REFERENCES "ivf_embryo_transfer_record"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
