import {MigrationInterface, QueryRunner} from "typeorm";

export class LabourMgt1661307710555 implements MigrationInterface {
    name = 'LabourMgt1661307710555'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP CONSTRAINT "FK_5b8d3603d63505747194cd3518d"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP CONSTRAINT "FK_6803a1e2c5fb855dcfa3695ff80"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP CONSTRAINT "FK_a0fc19ad7467974fc103fbfeb69"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP CONSTRAINT "FK_bbdd4a7a35a0e0082b531b4fc38"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "drugsAdministered"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "administeredVitaminK"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "timeOfBirth"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "transferredTo"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "pediatricianId"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "isMotherAlive"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "babyCried"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "negativeRH"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "dateOfBirth"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "deliveryType"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "bleeading"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "placentaComplete"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "apgarScore"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "sexOfBaby"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "administeredOxytocin"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "isBabyAlive"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "cervicalPosition"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "administeredDrugs"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "cervicalLength"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "isFalseLabour"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "hasPassedUrine"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "enrollmentId"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "positionOfFoetus"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "fetalLies"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP CONSTRAINT "REL_a0fc19ad7467974fc103fbfeb6"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "request_id"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "timeOfMeasurement"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "examinerId"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "cervicalEffacement"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "administeredCyatacin"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "dateOfMeasurement"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "previousPregnancyExperience"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "previousPregnancyOutcome"`);
        await queryRunner.query(`ALTER TABLE "patient_requests" ADD "labour_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "delivery_type" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "is_mother_alive" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "is_baby_alive" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "administered_oxytocin" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "placenta_delivered" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "normal_bleeding" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "date_of_birth" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "time_of_birth" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "baby_cried_immediately" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "sex_of_baby" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "apgar_score" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "administered_vitamin_k" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "mother_rh_negative" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "drugs_administered" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "transferred_to" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "patient_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "pediatrician_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "labour_sign" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "position_of_foetus" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "fetal_lie" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "cervical_length" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "cervical_effacement" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "cervical_position" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "has_passed_urine" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "administered_oxytocin" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "administered_other_drugs" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "enrollment_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "patient_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "risk_score" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "previous_pregnancy_outcome" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "history_low_birth_weight" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "previous_pregnancy_experience" text`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "patient_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ALTER COLUMN "weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ALTER COLUMN "height" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ALTER COLUMN "weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patient_requests" ADD CONSTRAINT "FK_0e2ff1ae49ff6be0efc6c99e6bc" FOREIGN KEY ("labour_id") REFERENCES "labour_enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD CONSTRAINT "FK_c456d37c62e7dfe0b2032761119" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD CONSTRAINT "FK_ae0fa94764e5d6d2c789f7d2dbc" FOREIGN KEY ("pediatrician_id") REFERENCES "staff_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD CONSTRAINT "FK_63611dc4f3e99882c2b1179c363" FOREIGN KEY ("enrollment_id") REFERENCES "labour_enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD CONSTRAINT "FK_69efd99ad56d8096d88b0fa1c08" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD CONSTRAINT "FK_60be655a11716a773168aa0c9d4" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP CONSTRAINT "FK_60be655a11716a773168aa0c9d4"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP CONSTRAINT "FK_69efd99ad56d8096d88b0fa1c08"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP CONSTRAINT "FK_63611dc4f3e99882c2b1179c363"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP CONSTRAINT "FK_ae0fa94764e5d6d2c789f7d2dbc"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP CONSTRAINT "FK_c456d37c62e7dfe0b2032761119"`);
        await queryRunner.query(`ALTER TABLE "patient_requests" DROP CONSTRAINT "FK_0e2ff1ae49ff6be0efc6c99e6bc"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ALTER COLUMN "weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ALTER COLUMN "height" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ALTER COLUMN "weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "patient_id"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "previous_pregnancy_experience"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "history_low_birth_weight"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "previous_pregnancy_outcome"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "risk_score"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "patient_id"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "enrollment_id"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "administered_other_drugs"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "administered_oxytocin"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "has_passed_urine"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "cervical_position"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "cervical_effacement"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "cervical_length"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "fetal_lie"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "position_of_foetus"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "labour_sign"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "pediatrician_id"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "patient_id"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "transferred_to"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "drugs_administered"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "mother_rh_negative"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "administered_vitamin_k"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "apgar_score"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "sex_of_baby"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "baby_cried_immediately"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "time_of_birth"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "normal_bleeding"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "placenta_delivered"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "administered_oxytocin"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "is_baby_alive"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "is_mother_alive"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "delivery_type"`);
        await queryRunner.query(`ALTER TABLE "patient_requests" DROP COLUMN "labour_id"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "previousPregnancyOutcome" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "previousPregnancyExperience" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "dateOfMeasurement" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "administeredCyatacin" boolean`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "cervicalEffacement" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "examinerId" integer`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "timeOfMeasurement" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "request_id" integer`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD CONSTRAINT "REL_a0fc19ad7467974fc103fbfeb6" UNIQUE ("request_id")`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "fetalLies" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "positionOfFoetus" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "enrollmentId" integer`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "hasPassedUrine" boolean`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "isFalseLabour" boolean`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "cervicalLength" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "administeredDrugs" boolean`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "cervicalPosition" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "isBabyAlive" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "administeredOxytocin" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "sexOfBaby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "apgarScore" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "placentaComplete" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "bleeading" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "deliveryType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "dateOfBirth" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "negativeRH" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "babyCried" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "isMotherAlive" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "pediatricianId" integer`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "transferredTo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "timeOfBirth" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "administeredVitaminK" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "drugsAdministered" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD CONSTRAINT "FK_bbdd4a7a35a0e0082b531b4fc38" FOREIGN KEY ("examinerId") REFERENCES "staff_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD CONSTRAINT "FK_a0fc19ad7467974fc103fbfeb69" FOREIGN KEY ("request_id") REFERENCES "patient_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD CONSTRAINT "FK_6803a1e2c5fb855dcfa3695ff80" FOREIGN KEY ("enrollmentId") REFERENCES "labour_enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD CONSTRAINT "FK_5b8d3603d63505747194cd3518d" FOREIGN KEY ("pediatricianId") REFERENCES "staff_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
