import {MigrationInterface, QueryRunner} from "typeorm";

export class DbMigration1627914798417 implements MigrationInterface {
    name = 'DbMigration1627914798417'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "is_staff"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "departments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_next_of_kins" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "consulting_rooms" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "services" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "hmo_companies" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "hmo_types" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "hmo_schemes" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "room_categories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "admission_care_givers" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "nicu-accommodations" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "nicu" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_vitals" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "admission_clinical_tasks" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "lab_test_categories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "lab_tests" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_documents" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_diagnoses" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "immunizations" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "drug_categories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "drug_generics" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "drug_manufacturers" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "vendors" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "drug_batches" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "drugs" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "service_costs" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_request_items" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_enrollments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "antenatal_enrollments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_requests" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "store_inventories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_consumables" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_allergens" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_notes" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_physical_exams" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_antenatals" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_histories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_past_diagnoses" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "encounters" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "staff_id" integer`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "UQ_76612193361e0b179d8530a2d4e" UNIQUE ("staff_id")`);
        await queryRunner.query(`ALTER TABLE "vouchers" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "specializations" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "staff_details" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_logged_in" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cafeteria_items" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "performance_appraisal_periods" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "performance_indicators" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "performance_appraisals" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "performance_comments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "performance_indicator_reports" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "supervisor_evalutions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluation_reports" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "roasters" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "leave_categories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "salary_allowances" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "salary_deductions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "salary_payment_deductions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "salary_payments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "salary_payment_allowances" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "cafeteria_inventories" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_activities" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "requisitions" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "service_logs" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "antenatal_visits" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_alerts" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_fluid_charts" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patient_review_of_systems" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_down_regulation_charts" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "ivf_hcg_administration_charts" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_enrollments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "labour_vitals" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "antenatal_packages" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "lab_groups" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "lab_group_tests" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "lab_parameters" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "request_types" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "lab_specimens" ADD "old_id" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "FK_76612193361e0b179d8530a2d4e" FOREIGN KEY ("staff_id") REFERENCES "staff_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "FK_76612193361e0b179d8530a2d4e"`);
        await queryRunner.query(`ALTER TABLE "lab_specimens" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "request_types" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "lab_parameters" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "lab_group_tests" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "lab_groups" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "antenatal_packages" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "labour_vitals" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "labour_risk_assessments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "labour_measurements" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "labour_delivery_records" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "labour_enrollments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_hcg_administration_charts" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_down_regulation_charts" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_review_of_systems" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_fluid_charts" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_alerts" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "antenatal_visits" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "service_logs" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "requisitions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_activities" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "cafeteria_inventories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "salary_payment_allowances" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "salary_payments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "salary_payment_deductions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "salary_deductions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "salary_allowances" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "leave_categories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "roasters" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluation_reports" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "supervisor_evalutions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "performance_indicator_reports" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "performance_comments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "performance_appraisals" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "performance_indicators" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "performance_appraisal_periods" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "cafeteria_items" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_logged_in"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "staff_details" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "specializations" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "vouchers" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "UQ_76612193361e0b179d8530a2d4e"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "staff_id"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "encounters" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_past_diagnoses" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_histories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_antenatals" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_physical_exams" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_notes" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_allergens" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_consumables" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "store_inventories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_requests" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "antenatal_enrollments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "ivf_enrollments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_request_items" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "service_costs" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "drugs" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "drug_batches" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "vendors" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "drug_manufacturers" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "drug_generics" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "drug_categories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "immunizations" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_diagnoses" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_documents" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "lab_tests" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "lab_test_categories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "admission_clinical_tasks" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_vitals" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "nicu" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "nicu-accommodations" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "admission_care_givers" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "room_categories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "hmo_schemes" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "hmo_types" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "hmo_companies" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "consulting_rooms" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patient_next_of_kins" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "old_id"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "is_staff" boolean NOT NULL DEFAULT false`);
    }

}
